/** football-data.org 3-letter TLA → app ISO-style team codes. */
export const TLA_TO_CODE: Record<string, string> = {
  MEX: "MX",
  RSA: "ZA",
  KOR: "KR",
  CZE: "CZ",
  CAN: "CA",
  USA: "US",
  PAR: "PY",
  QAT: "QA",
  SUI: "CH",
  BRA: "BR",
  MAR: "MA",
  SCO: "SF",
  HAI: "HT",
  AUS: "AU",
  TUR: "TR",
  GER: "DE",
  CUW: "CW",
  NED: "NL",
  JPN: "JP",
  CIV: "CI",
  ECU: "EC",
  SWE: "SE",
  TUN: "TN",
  ESP: "ES",
  CPV: "CV",
  BEL: "BE",
  EGY: "EG",
  URU: "UY",
  KSA: "SA",
  IRN: "IR",
  NZL: "NZ",
  FRA: "FR",
  SEN: "SN",
  IRQ: "IQ",
  NOR: "NO",
  ARG: "AR",
  ALG: "DZ",
  AUT: "AT",
  JOR: "JO",
  POR: "PT",
  COD: "CD",
  ENG: "EN",
  CRO: "HR",
  GHA: "GH",
  PAN: "PA",
  UZB: "UZ",
  COL: "CO",
  BIH: "BA",
};

export function tlaToCode(tla: string | null | undefined): string | null {
  if (!tla) return null;
  const key = tla.toUpperCase();
  return TLA_TO_CODE[key] ?? key.slice(0, 2);
}
