class SeedMatch {
  const SeedMatch({
    required this.homeAr,
    required this.homeEn,
    required this.awayAr,
    required this.awayEn,
    required this.homeCode,
    required this.awayCode,
    required this.kickoff,
  });

  final String homeAr;
  final String homeEn;
  final String awayAr;
  final String awayEn;
  final String homeCode;
  final String awayCode;
  final String kickoff;
}

const groupMatches = [
  SeedMatch(homeAr: 'المكسيك', homeEn: 'Mexico', awayAr: 'جنوب إفريقيا', awayEn: 'South Africa', homeCode: 'MX', awayCode: 'ZA', kickoff: '2026-06-11 22:00:00+03'),
  SeedMatch(homeAr: 'كوريا الجنوبية', homeEn: 'South Korea', awayAr: 'التشيك', awayEn: 'Czech Republic', homeCode: 'KR', awayCode: 'CZ', kickoff: '2026-06-12 05:00:00+03'),
  SeedMatch(homeAr: 'كندا', homeEn: 'Canada', awayAr: 'البوسنة والهرسك', awayEn: 'Bosnia', homeCode: 'CA', awayCode: 'BA', kickoff: '2026-06-12 22:00:00+03'),
  SeedMatch(homeAr: 'الولايات المتحدة', homeEn: 'USA', awayAr: 'باراغواي', awayEn: 'Paraguay', homeCode: 'US', awayCode: 'PY', kickoff: '2026-06-13 04:00:00+03'),
  SeedMatch(homeAr: 'قطر', homeEn: 'Qatar', awayAr: 'سويسرا', awayEn: 'Switzerland', homeCode: 'QA', awayCode: 'CH', kickoff: '2026-06-13 22:00:00+03'),
  SeedMatch(homeAr: 'البرازيل', homeEn: 'Brazil', awayAr: 'المغرب', awayEn: 'Morocco', homeCode: 'BR', awayCode: 'MA', kickoff: '2026-06-14 01:00:00+03'),
  SeedMatch(homeAr: 'اسكتلندا', homeEn: 'Scotland', awayAr: 'هايتي', awayEn: 'Haiti', homeCode: 'SF', awayCode: 'HT', kickoff: '2026-06-14 04:00:00+03'),
  SeedMatch(homeAr: 'أستراليا', homeEn: 'Australia', awayAr: 'تركيا', awayEn: 'Turkey', homeCode: 'AU', awayCode: 'TR', kickoff: '2026-06-14 07:00:00+03'),
  SeedMatch(homeAr: 'ألمانيا', homeEn: 'Germany', awayAr: 'كوراساو', awayEn: 'Curaçao', homeCode: 'DE', awayCode: 'CW', kickoff: '2026-06-14 20:00:00+03'),
  SeedMatch(homeAr: 'هولندا', homeEn: 'Netherlands', awayAr: 'اليابان', awayEn: 'Japan', homeCode: 'NL', awayCode: 'JP', kickoff: '2026-06-14 23:00:00+03'),
  SeedMatch(homeAr: 'ساحل العاج', homeEn: 'Ivory Coast', awayAr: 'الإكوادور', awayEn: 'Ecuador', homeCode: 'CI', awayCode: 'EC', kickoff: '2026-06-15 02:00:00+03'),
  SeedMatch(homeAr: 'السويد', homeEn: 'Sweden', awayAr: 'تونس', awayEn: 'Tunisia', homeCode: 'SE', awayCode: 'TN', kickoff: '2026-06-15 05:00:00+03'),
  SeedMatch(homeAr: 'إسبانيا', homeEn: 'Spain', awayAr: 'الرأس الأخضر', awayEn: 'Cape Verde', homeCode: 'ES', awayCode: 'CV', kickoff: '2026-06-15 19:00:00+03'),
  SeedMatch(homeAr: 'بلجيكا', homeEn: 'Belgium', awayAr: 'مصر', awayEn: 'Egypt', homeCode: 'BE', awayCode: 'EG', kickoff: '2026-06-15 22:00:00+03'),
  SeedMatch(homeAr: 'أوروغواي', homeEn: 'Uruguay', awayAr: 'السعودية', awayEn: 'Saudi Arabia', homeCode: 'UY', awayCode: 'SA', kickoff: '2026-06-16 01:00:00+03'),
  SeedMatch(homeAr: 'إيران', homeEn: 'Iran', awayAr: 'نيوزيلندا', awayEn: 'New Zealand', homeCode: 'IR', awayCode: 'NZ', kickoff: '2026-06-16 04:00:00+03'),
  SeedMatch(homeAr: 'فرنسا', homeEn: 'France', awayAr: 'السنغال', awayEn: 'Senegal', homeCode: 'FR', awayCode: 'SN', kickoff: '2026-06-16 22:00:00+03'),
  SeedMatch(homeAr: 'العراق', homeEn: 'Iraq', awayAr: 'النرويج', awayEn: 'Norway', homeCode: 'IQ', awayCode: 'NO', kickoff: '2026-06-17 01:00:00+03'),
  SeedMatch(homeAr: 'الأرجنتين', homeEn: 'Argentina', awayAr: 'الجزائر', awayEn: 'Algeria', homeCode: 'AR', awayCode: 'DZ', kickoff: '2026-06-17 04:00:00+03'),
  SeedMatch(homeAr: 'النمسا', homeEn: 'Austria', awayAr: 'الأردن', awayEn: 'Jordan', homeCode: 'AT', awayCode: 'JO', kickoff: '2026-06-17 07:00:00+03'),
  SeedMatch(homeAr: 'البرتغال', homeEn: 'Portugal', awayAr: 'جمهورية الكونغو ديموقراطية', awayEn: 'DR Congo', homeCode: 'PT', awayCode: 'CD', kickoff: '2026-06-17 20:00:00+03'),
  SeedMatch(homeAr: 'إنجلترا', homeEn: 'England', awayAr: 'كرواتيا', awayEn: 'Croatia', homeCode: 'EN', awayCode: 'HR', kickoff: '2026-06-17 23:00:00+03'),
  SeedMatch(homeAr: 'غانا', homeEn: 'Ghana', awayAr: 'بنما', awayEn: 'Panama', homeCode: 'GH', awayCode: 'PA', kickoff: '2026-06-18 02:00:00+03'),
  SeedMatch(homeAr: 'أوزبكستان', homeEn: 'Uzbekistan', awayAr: 'كولومبيا', awayEn: 'Colombia', homeCode: 'UZ', awayCode: 'CO', kickoff: '2026-06-18 05:00:00+03'),
  SeedMatch(homeAr: 'التشيك', homeEn: 'Czech Republic', awayAr: 'جنوب إفريقيا', awayEn: 'South Africa', homeCode: 'CZ', awayCode: 'ZA', kickoff: '2026-06-18 19:00:00+03'),
  SeedMatch(homeAr: 'سويسرا', homeEn: 'Switzerland', awayAr: 'البوسنة والهرسك', awayEn: 'Bosnia', homeCode: 'CH', awayCode: 'BA', kickoff: '2026-06-18 22:00:00+03'),
  SeedMatch(homeAr: 'كندا', homeEn: 'Canada', awayAr: 'قطر', awayEn: 'Qatar', homeCode: 'CA', awayCode: 'QA', kickoff: '2026-06-19 01:00:00+03'),
  SeedMatch(homeAr: 'المكسيك', homeEn: 'Mexico', awayAr: 'كوريا الجنوبية', awayEn: 'South Korea', homeCode: 'MX', awayCode: 'KR', kickoff: '2026-06-19 04:00:00+03'),
  SeedMatch(homeAr: 'الولايات المتحدة', homeEn: 'USA', awayAr: 'أستراليا', awayEn: 'Australia', homeCode: 'US', awayCode: 'AU', kickoff: '2026-06-19 22:00:00+03'),
  SeedMatch(homeAr: 'اسكتلندا', homeEn: 'Scotland', awayAr: 'المغرب', awayEn: 'Morocco', homeCode: 'SF', awayCode: 'MA', kickoff: '2026-06-20 01:00:00+03'),
  SeedMatch(homeAr: 'البرازيل', homeEn: 'Brazil', awayAr: 'هايتي', awayEn: 'Haiti', homeCode: 'BR', awayCode: 'HT', kickoff: '2026-06-20 03:30:00+03'),
  SeedMatch(homeAr: 'تركيا', homeEn: 'Turkey', awayAr: 'باراغواي', awayEn: 'Paraguay', homeCode: 'TR', awayCode: 'PY', kickoff: '2026-06-20 06:00:00+03'),
  SeedMatch(homeAr: 'هولندا', homeEn: 'Netherlands', awayAr: 'السويد', awayEn: 'Sweden', homeCode: 'NL', awayCode: 'SE', kickoff: '2026-06-20 20:00:00+03'),
  SeedMatch(homeAr: 'ألمانيا', homeEn: 'Germany', awayAr: 'ساحل العاج', awayEn: 'Ivory Coast', homeCode: 'DE', awayCode: 'CI', kickoff: '2026-06-20 23:00:00+03'),
  SeedMatch(homeAr: 'الإكوادور', homeEn: 'Ecuador', awayAr: 'كوراساو', awayEn: 'Curaçao', homeCode: 'EC', awayCode: 'CW', kickoff: '2026-06-21 03:00:00+03'),
  SeedMatch(homeAr: 'تونس', homeEn: 'Tunisia', awayAr: 'اليابان', awayEn: 'Japan', homeCode: 'TN', awayCode: 'JP', kickoff: '2026-06-21 07:00:00+03'),
  SeedMatch(homeAr: 'إسبانيا', homeEn: 'Spain', awayAr: 'السعودية', awayEn: 'Saudi Arabia', homeCode: 'ES', awayCode: 'SA', kickoff: '2026-06-21 19:00:00+03'),
  SeedMatch(homeAr: 'بلجيكا', homeEn: 'Belgium', awayAr: 'إيران', awayEn: 'Iran', homeCode: 'BE', awayCode: 'IR', kickoff: '2026-06-21 22:00:00+03'),
  SeedMatch(homeAr: 'أوروغواي', homeEn: 'Uruguay', awayAr: 'الرأس الأخضر', awayEn: 'Cape Verde', homeCode: 'UY', awayCode: 'CV', kickoff: '2026-06-22 01:00:00+03'),
  SeedMatch(homeAr: 'نيوزيلندا', homeEn: 'New Zealand', awayAr: 'مصر', awayEn: 'Egypt', homeCode: 'NZ', awayCode: 'EG', kickoff: '2026-06-22 04:00:00+03'),
  SeedMatch(homeAr: 'النرويج', homeEn: 'Norway', awayAr: 'السنغال', awayEn: 'Senegal', homeCode: 'NO', awayCode: 'SN', kickoff: '2026-06-22 22:00:00+03'),
  SeedMatch(homeAr: 'فرنسا', homeEn: 'France', awayAr: 'العراق', awayEn: 'Iraq', homeCode: 'FR', awayCode: 'IQ', kickoff: '2026-06-23 01:00:00+03'),
  SeedMatch(homeAr: 'الأرجنتين', homeEn: 'Argentina', awayAr: 'النمسا', awayEn: 'Austria', homeCode: 'AR', awayCode: 'AT', kickoff: '2026-06-23 04:00:00+03'),
  SeedMatch(homeAr: 'الأردن', homeEn: 'Jordan', awayAr: 'الجزائر', awayEn: 'Algeria', homeCode: 'JO', awayCode: 'DZ', kickoff: '2026-06-23 07:00:00+03'),
  SeedMatch(homeAr: 'إنجلترا', homeEn: 'England', awayAr: 'غانا', awayEn: 'Ghana', homeCode: 'EN', awayCode: 'GH', kickoff: '2026-06-23 20:00:00+03'),
  SeedMatch(homeAr: 'بنما', homeEn: 'Panama', awayAr: 'كرواتيا', awayEn: 'Croatia', homeCode: 'PA', awayCode: 'HR', kickoff: '2026-06-23 23:00:00+03'),
  SeedMatch(homeAr: 'البرتغال', homeEn: 'Portugal', awayAr: 'أوزبكستان', awayEn: 'Uzbekistan', homeCode: 'PT', awayCode: 'UZ', kickoff: '2026-06-24 02:00:00+03'),
  SeedMatch(homeAr: 'كولومبيا', homeEn: 'Colombia', awayAr: 'جمهورية الكونغو ديموقراطية', awayEn: 'DR Congo', homeCode: 'CO', awayCode: 'CD', kickoff: '2026-06-24 05:00:00+03'),
  SeedMatch(homeAr: 'اسكتلندا', homeEn: 'Scotland', awayAr: 'البرازيل', awayEn: 'Brazil', homeCode: 'SF', awayCode: 'BR', kickoff: '2026-06-24 22:00:00+03'),
  SeedMatch(homeAr: 'المغرب', homeEn: 'Morocco', awayAr: 'هايتي', awayEn: 'Haiti', homeCode: 'MA', awayCode: 'HT', kickoff: '2026-06-24 22:00:00+03'),
  SeedMatch(homeAr: 'سويسرا', homeEn: 'Switzerland', awayAr: 'كندا', awayEn: 'Canada', homeCode: 'CH', awayCode: 'CA', kickoff: '2026-06-25 01:00:00+03'),
  SeedMatch(homeAr: 'البوسنة والهرسك', homeEn: 'Bosnia', awayAr: 'قطر', awayEn: 'Qatar', homeCode: 'BA', awayCode: 'QA', kickoff: '2026-06-25 01:00:00+03'),
  SeedMatch(homeAr: 'التشيك', homeEn: 'Czech Republic', awayAr: 'المكسيك', awayEn: 'Mexico', homeCode: 'CZ', awayCode: 'MX', kickoff: '2026-06-25 04:00:00+03'),
  SeedMatch(homeAr: 'جنوب إفريقيا', homeEn: 'South Africa', awayAr: 'كوريا الجنوبية', awayEn: 'South Korea', homeCode: 'ZA', awayCode: 'KR', kickoff: '2026-06-25 04:00:00+03'),
  SeedMatch(homeAr: 'كوراساو', homeEn: 'Curaçao', awayAr: 'ساحل العاج', awayEn: 'Ivory Coast', homeCode: 'CW', awayCode: 'CI', kickoff: '2026-06-25 20:00:00+03'),
  SeedMatch(homeAr: 'الإكوادور', homeEn: 'Ecuador', awayAr: 'ألمانيا', awayEn: 'Germany', homeCode: 'EC', awayCode: 'DE', kickoff: '2026-06-25 20:00:00+03'),
  SeedMatch(homeAr: 'اليابان', homeEn: 'Japan', awayAr: 'السويد', awayEn: 'Sweden', homeCode: 'JP', awayCode: 'SE', kickoff: '2026-06-25 23:00:00+03'),
  SeedMatch(homeAr: 'تونس', homeEn: 'Tunisia', awayAr: 'هولندا', awayEn: 'Netherlands', homeCode: 'TN', awayCode: 'NL', kickoff: '2026-06-25 23:00:00+03'),
  SeedMatch(homeAr: 'تركيا', homeEn: 'Turkey', awayAr: 'الولايات المتحدة', awayEn: 'USA', homeCode: 'TR', awayCode: 'US', kickoff: '2026-06-26 03:00:00+03'),
  SeedMatch(homeAr: 'باراغواي', homeEn: 'Paraguay', awayAr: 'أستراليا', awayEn: 'Australia', homeCode: 'PY', awayCode: 'AU', kickoff: '2026-06-26 03:00:00+03'),
  SeedMatch(homeAr: 'الرأس الأخضر', homeEn: 'Cape Verde', awayAr: 'السعودية', awayEn: 'Saudi Arabia', homeCode: 'CV', awayCode: 'SA', kickoff: '2026-06-26 19:00:00+03'),
  SeedMatch(homeAr: 'أوروغواي', homeEn: 'Uruguay', awayAr: 'إسبانيا', awayEn: 'Spain', homeCode: 'UY', awayCode: 'ES', kickoff: '2026-06-26 19:00:00+03'),
  SeedMatch(homeAr: 'مصر', homeEn: 'Egypt', awayAr: 'إيران', awayEn: 'Iran', homeCode: 'EG', awayCode: 'IR', kickoff: '2026-06-26 22:00:00+03'),
  SeedMatch(homeAr: 'نيوزيلندا', homeEn: 'New Zealand', awayAr: 'بلجيكا', awayEn: 'Belgium', homeCode: 'NZ', awayCode: 'BE', kickoff: '2026-06-26 22:00:00+03'),
  SeedMatch(homeAr: 'السنغال', homeEn: 'Senegal', awayAr: 'العراق', awayEn: 'Iraq', homeCode: 'SN', awayCode: 'IQ', kickoff: '2026-06-27 01:00:00+03'),
  SeedMatch(homeAr: 'النرويج', homeEn: 'Norway', awayAr: 'فرنسا', awayEn: 'France', homeCode: 'NO', awayCode: 'FR', kickoff: '2026-06-27 01:00:00+03'),
  SeedMatch(homeAr: 'الجزائر', homeEn: 'Algeria', awayAr: 'النمسا', awayEn: 'Austria', homeCode: 'DZ', awayCode: 'AT', kickoff: '2026-06-27 04:00:00+03'),
  SeedMatch(homeAr: 'كولومبيا', homeEn: 'Colombia', awayAr: 'البرتغال', awayEn: 'Portugal', homeCode: 'CO', awayCode: 'PT', kickoff: '2026-06-27 04:00:00+03'),
  SeedMatch(homeAr: 'جمهورية الكونغو ديموقراطية', homeEn: 'DR Congo', awayAr: 'أوزبكستان', awayEn: 'Uzbekistan', homeCode: 'CD', awayCode: 'UZ', kickoff: '2026-06-27 04:00:00+03'),
  SeedMatch(homeAr: 'كرواتيا', homeEn: 'Croatia', awayAr: 'غانا', awayEn: 'Ghana', homeCode: 'HR', awayCode: 'GH', kickoff: '2026-06-27 19:00:00+03'),
  SeedMatch(homeAr: 'بنما', homeEn: 'Panama', awayAr: 'إنجلترا', awayEn: 'England', homeCode: 'PA', awayCode: 'EN', kickoff: '2026-06-27 19:00:00+03'),
];
